networks:
  lecoursier:
    external: true
  traefik-public:
    external: true

services:
  app-develop:
    image: josemokeni/lecoursier-laravel-develop:latest
    networks:
      - lecoursier
      - traefik-public
    volumes:
      - ./docker/firebase/service-account.json:/var/www/html/storage/app/json/service-account.json
      - ./.env.develop:/var/www/html/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.app-develop.rule=Host(`lecoursier.develop.josemokeni.cloud`)"
      - "traefik.http.routers.app-develop.entrypoints=websecure"
      - "traefik.http.routers.app-develop.tls.certresolver=leresolver"
      - "traefik.http.services.app-develop.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

  app-staging:
    image: josemokeni/lecoursier-laravel-staging:latest
    networks:
      - lecoursier
      - traefik-public
    volumes:
      - ./docker/firebase/service-account.json:/var/www/html/storage/app/json/service-account.json
      - ./.env.staging:/var/www/html/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.app-staging.rule=Host(`lecoursier.staging.josemokeni.cloud`)"
      - "traefik.http.routers.app-staging.entrypoints=websecure"
      - "traefik.http.routers.app-staging.tls.certresolver=leresolver"
      - "traefik.http.services.app-staging.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

  app:
    image: josemokeni/lecoursier-laravel:latest
    networks:
      - lecoursier
      - traefik-public
    volumes:
      - ./docker/firebase/service-account.json:/var/www/html/storage/app/json/service-account.json
      - ./.env:/var/www/html/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`lecoursier.josemokeni.cloud`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=leresolver"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --cleanup --rolling-restart
    environment:
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - lecoursier
    restart: unless-stopped
