apiVersion: v1
kind: ConfigMap
metadata:
  name: lecoursier-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_DEBUG: "false"
  APP_TIMEZONE: "UTC"
  APP_URL: "http://lecoursier.kubernetes:30448"

  CENTRAL_DOMAINS: lecoursier.kubernetes

  DB_CONNECTION: "pgsql"
  DB_PORT: "5432"

  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: database

  MAIL_MAILER: "mailhog"
  MAIL_SCHEME: "null"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MAIL_FROM_ADDRESS: "do-not-reply@lecoursier.app"
  MAIL_FROM_NAME: "${APP_NAME}"
