#!/bin/bash

# Traefik Deployment Script for LeCoursier Kubernetes
# This script deploys the application with Traefik ingress controller for automatic HTTPS

set -e

echo "🚀 Starting Traefik deployment for LeCoursier..."

# Function to wait for deployment
wait_for_deployment() {
    local name=$1
    echo "⏳ Waiting for $name to be ready..."
    kubectl wait --for=condition=available --timeout=300s deployment/$name
}

# Function to wait for pod
wait_for_pod() {
    local label=$1
    echo "⏳ Waiting for pods with label $label to be ready..."
    kubectl wait --for=condition=ready --timeout=300s pod -l $label
}

echo "📦 Applying Traefik RBAC..."
kubectl apply -f traefik-rbac.yaml

echo "🔧 Creating Traefik configuration..."
kubectl apply -f traefik-config.yaml

echo "💾 Creating Traefik persistent volume..."
kubectl apply -f traefik-pvc.yaml

echo "🌐 Deploying Traefik ingress controller..."
kubectl apply -f traefik-deployment.yaml
kubectl apply -f traefik-service.yaml

echo "⚙️ Applying Traefik middlewares..."
kubectl apply -f traefik-middlewares.yaml

# Wait for Traefik to be ready
wait_for_deployment traefik

echo "🗄️ Deploying PostgreSQL..."
kubectl apply -f postgres-configmap.yaml
kubectl apply -f postgres-secret.yaml
kubectl apply -f postgres-pvc.yaml
kubectl apply -f postgres-deployment.yaml
kubectl apply -f postgres-service.yaml

echo "🔴 Deploying Redis..."
kubectl apply -f redis-configmap.yaml
kubectl apply -f redis-pvc.yaml
kubectl apply -f redis-deployment.yaml
kubectl apply -f redis-service.yaml

echo "📧 Deploying Mailhog..."
kubectl apply -f mailhog-deployment.yaml
kubectl apply -f mailhog-service.yaml
kubectl apply -f mailhog-web-service.yaml

echo "🔧 Deploying Redis Commander..."
kubectl apply -f redis-commander-deployment.yaml
kubectl apply -f redis-commander-service.yaml

echo "🐘 Deploying pgAdmin..."
kubectl apply -f pgadmin-secret.yaml
kubectl apply -f pgadmin-pvc.yaml
kubectl apply -f pgadmin-deployment.yaml
kubectl apply -f pgadmin-service.yaml

# Wait for databases to be ready
wait_for_pod "app=postgres"
wait_for_pod "app=redis"

echo "🔥 Deploying Firebase configuration..."
kubectl apply -f firebase-secret.yaml

echo "🚀 Deploying LeCoursier application..."
kubectl apply -f app-configmap.yaml
kubectl apply -f app-secret.yaml
kubectl apply -f app-deployment.yaml
kubectl apply -f app-service.yaml

# Wait for application to be ready
wait_for_deployment lecoursier-app

echo "🌐 Applying Traefik ingress..."
kubectl apply -f traefik-ingress.yaml

echo "✅ Deployment completed successfully!"

echo ""
echo "📊 Deployment Status:"
kubectl get pods -o wide
echo ""
kubectl get services
echo ""
kubectl get ingress

echo ""
echo "🌐 Access URLs:"
echo "📊 Traefik Dashboard: http://localhost:8080 (or your-cluster-ip:8080)"
echo "🚀 Application: https://lecoursier.example.com (configure your domain)"
echo "📧 Mailhog: https://mailhog.example.com"
echo "🔴 Redis Commander: https://redis.example.com"
echo "🐘 pgAdmin: https://pgadmin.example.com"

echo ""
echo "⚠️  Important Notes:"
echo "1. Update traefik-config.yaml with your actual email for Let's Encrypt"
echo "2. Update traefik-ingress.yaml with your actual domain names"
echo "3. Make sure your domain DNS points to your cluster's external IP"
echo "4. SSL certificates will be automatically generated by Let's Encrypt"
echo ""
echo "🔧 Next Steps:"
echo "1. Run database migrations:"
echo "   kubectl exec -it \$(kubectl get pods -l app=lecoursier -o jsonpath='{.items[0].metadata.name}') -- php artisan migrate --force"
echo ""
echo "2. Check Traefik dashboard for certificate status"
echo "3. Monitor logs: kubectl logs -l app=traefik -f"
