apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AcGdhZG1pbi5jb20= # base64 encoded 'admin@pgadmin.com'
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4= # base64 encoded 'admin'
